using Avalonia.Interactivity;
using GenHub.Common.Controls;
using GenHub.Features.Tools.ModBuilder.ViewModels;
using System.Collections.Generic;

namespace GenHub.Features.Tools.ModBuilder.Views;

/// <summary>
/// Dialog window for picking project files and directories to add to a bundle item.
/// </summary>
public partial class ProjectItemPickerDialog : GenHubWindow
{
    /// <summary>
    /// Gets the list of selected patterns generated by this dialog.
    /// </summary>
    public List<string> ResultPatterns { get; private set; } = [];

    /// <summary>
    /// Initializes a new instance of the <see cref="ProjectItemPickerDialog"/> class.
    /// </summary>
    public ProjectItemPickerDialog()
    {
        InitializeComponent();
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProjectItemPickerDialog"/> class with a ViewModel.
    /// </summary>
    /// <param name="viewModel">The ViewModel.</param>
    public ProjectItemPickerDialog(ProjectItemPickerViewModel viewModel)
        : this()
    {
        DataContext = viewModel;
    }

    private void OnCancelClick(object? sender, RoutedEventArgs e)
    {
        Close(false);
    }

    private void OnConfirmClick(object? sender, RoutedEventArgs e)
    {
        if (DataContext is ProjectItemPickerViewModel vm)
        {
            ResultPatterns = vm.GetGeneratedPatterns();
            Close(true);
        }
        else
        {
            Close(false);
        }
    }
}
