sonar.cpd.exclusions=GenHub/GenHub/Features/Info/Services/DefaultInfoContentProvider.cs,GenHub/GenHub/Features/Content/Services/**/*ProfileReconciler.cs,GenHub/GenHub.Core/Helpers/GameSettingsMapper.cs,docs/**,GenHub/GenHub/SampleCatalogs/**
sonar.exclusions=docs/**
sonar.coverage.exclusions=scripts/**
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S2077
sonar.issue.ignore.multicriteria.e1.resourceKey=GenHub/GenHub.Core/Constants/GenLauncherConstants.cs
sonar.issue.ignore.multicriteria.e2.ruleKey=csharpsquid:S6605
sonar.issue.ignore.multicriteria.e2.resourceKey=GenHub/GenHub.Core/Constants/GenLauncherConstants.cs
