<#
.SYNOPSIS
    Generates genhub:// test shortcuts for THIS machine. On Windows: .reg + .url.
    On Linux/macOS (pwsh): delegates to generate-test-shortcuts.sh.

.DESCRIPTION
    The .reg and .url files in this folder reference absolute paths (the debug
    build of GenHub.Windows.exe, and the catalog JSON). Those paths are
    machine-specific, so the committed versions cannot be shared. This script
    regenerates both files from templates using paths resolved relative to the
    script's own location, then you can double-click them locally.

    Run it once after cloning (or after the debug exe path changes, e.g. a new
    TFM) before using the .reg / .url files.

    On Linux/macOS this script delegates to generate-test-shortcuts.sh (bash),
    which emits native .desktop / .command / .webloc / .app handlers. See
    README.md.

.PARAMETER Config
    Build configuration to point at. Defaults to Debug.

.PARAMETER Force
    Overwrite the generated files without prompting. Without this flag the
    script asks for confirmation when the files already exist.

.EXAMPLE
    ./generate-test-shortcuts.ps1
    Generates both files pointing at the Debug build.

.EXAMPLE
    ./generate-test-shortcuts.ps1 -Config Release -Force
    Points at the Release build and overwrites silently.
#>
[CmdletBinding()]
param(
    [string]$Config = "Debug",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# pwsh on Linux/macOS: the native generators live in the bash script.
if ($IsLinux -or $IsMacOS) {
    $bash = Get-Command bash -ErrorAction SilentlyContinue
    if (-not $bash) {
        throw "Linux/macOS shortcut generation is implemented in generate-test-shortcuts.sh, but bash was not found on PATH."
    }
    $env:CONFIG = $Config
    if ($Force) { $env:FORCE = "1" }
    & $bash.Source (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Definition) "generate-test-shortcuts.sh")
    if ($LASTEXITCODE -ne 0) {
        throw "generate-test-shortcuts.sh exited with code $LASTEXITCODE."
    }
    return
}

# Resolve everything relative to THIS script's location so the script works no
# matter what the current directory is.
$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$repoRoot    = Resolve-Path (Join-Path $scriptDir "..\..\..")
$catalogPath = Join-Path $scriptDir "genhub-test-catalog.catalog.json"
$windowsProj = Join-Path $repoRoot "GenHub\GenHub.Windows"

$exeName = "GenHub.Windows.exe"
$exeDir  = Join-Path $windowsProj "bin\$Config\net8.0-windows"
$exePath = Join-Path $exeDir $exeName

if (-not (Test-Path $catalogPath)) {
    throw "Catalog not found at '$catalogPath'. Re-run from the SampleCatalogs folder."
}

if (-not (Test-Path $exePath)) {
    Write-Warning "Debug exe not found at '$exePath'."
    Write-Warning "Build GenHub.Windows first:"
    Write-Warning "  dotnet build (Join-Path `$repoRoot 'GenHub.sln') -c $Config"
    Write-Warning "Or just launch the app once -- UriSchemeRegistrar self-registers the scheme."
    Write-Warning "Generating files anyway; the scheme will resolve once the exe exists."
}

# --- .reg file ---------------------------------------------------------------
# Single-quoted here-string so nothing in the registry body needs escaping.
# The exe path is spliced in via -replace on a placeholder, then backslashes
# are doubled for the registry's own escaping rules.
$regPath = Join-Path $scriptDir "register-genhub-scheme.reg"
$exeRegPath = $exePath -replace '\\', '\\'

$regContent = @'
Windows Registry Editor Version 5.00

; AUTO-GENERATED by generate-test-shortcuts.ps1 -- do not edit by hand.
; Registers the genhub:// URI scheme to point at the __CONFIG__ build of GenHub.Windows.exe
; for THIS machine. Double-click this file to merge it into HKCU (no admin required),
; then Subscribe-Test-Catalog.url will open GenHub and pass thed
; genhub://subscribe?url=... argument.
;
; NOTE: After a clean rebuild that changes the exe path, either re-run this script
; or launch GenHub.Windows.exe once -- UriSchemeRegistrar self-registers the scheme
; at the current exe location on every launch.

[HKEY_CURRENT_USER\Software\Classes\genhub]
@="URL:genhub protocol"
"URL Protocol"=""

[HKEY_CURRENT_USER\Software\Classes\genhub\DefaultIcon]
@="__EXE__REG__PATH__,0"

[HKEY_CURRENT_USER\Software\Classes\genhub\shell]

[HKEY_CURRENT_USER\Software\Classes\genhub\shell\open]

[HKEY_CURRENT_USER\Software\Classes\genhub\shell\open\command]
@="\"__EXE__REG__PATH__\" \"%1\""
'@ -replace '__CONFIG__', $Config `
   -replace '__EXE__REG__PATH__', $exeRegPath

# --- .url file ---------------------------------------------------------------
$urlPath = Join-Path $scriptDir "Subscribe-Test-Catalog.url"
$fileUri = "file:///" + ($catalogPath -replace '\\', '/')

$urlContent = @'
[InternetShortcut]
URL=genhub://subscribe?url=__FILEURI__
IDList=
IconFile=avares://GenHub/Assets/Icons/generalshub-icon.png
IconIndex=0
'@ -replace '__FILEURI__', $fileUri

foreach ($pair in @(@{Path = $regPath; Content = $regContent},
                    @{Path = $urlPath; Content = $urlContent})) {
    if ((Test-Path $pair.Path) -and -not $Force) {
        $rel = Resolve-Path $pair.Path -Relative
        $overwrite = Read-Host "$rel exists. Overwrite? [y/N]"
        if ($overwrite -notmatch '^[yY]') {
            Write-Host "Skipped $rel"
            continue
        }
    }
    Set-Content -Path $pair.Path -Value $pair.Content -Encoding ASCII -NoNewline
    Add-Content -Path $pair.Path -Value ""      # trailing newline
    Write-Host "Wrote $(Resolve-Path $pair.Path -Relative)"
}

Write-Host ""
Write-Host "Done. Next steps:"
Write-Host "  1. Double-click register-genhub-scheme.reg (or launch GenHub once to self-register)."
Write-Host "  2. Double-click Subscribe-Test-Catalog.url to test the subscribe flow."
